### ISSUE TITLE
Cruise signs not working

### ISSUE THREAD

**Issue by JoshuaCulwell** [APDevTeam/Movecraft#620]
**Describe the bug**
Cruise signs are not working in 8.0.0 Beta 2.
For some reason if signs are initialized as "Cruise: ON" and they are clicked a message is displayed saying cruise has been turned off and the sign changes to off but then the sign will not switch from "Cruise: OFF" to "Cruise: ON" again. 

**To Reproduce**
1. Create a craft that is able to cruise.
2. Add a "Cruise: OFF" sign
3. Pilot the craft
4. click on the "Cruise: OFF" sign
5. See error

**Expected behavior**
When a craft is being piloted and a cruise sign is clicked it will enable cruise in the direction of the sign.

**Versions (please complete the following information):**
 - Movecraft: 8.0.0 beta 2
 - Java JDK 17
 - Minecraft 1.20.1

**Comment by parsec42** [comment]
I have the same problem.

**Comment by TylerS1066** [comment]
I believe this was probably fixed in #618.  Can you try running [this dev build](https://github.com/APDevTeam/Movecraft/actions/runs/7364371741/artifacts/1140307743) on 1.20.4 to verify the issue is gone?

**Comment by JoshuaCulwell** [comment]
I just set up a 1.20.4 server and used the dev build you gave. The signs are working better than before (release sign doesn't make me edit when I click on the sign) however the cruise signs are still not working. If the sign is set to "Cruise: ON" before piloting the craft it immediately switches to "Cruise: OFF" which changed from before where it wanted me to click on it to change it to off. 
No matter what I do I cannot seem to make it switch from "Cruise: OFF" to "Cruise: ON" though.

**Comment by JoshuaCulwell** [comment]
After reviewing the code line 63 in the "CruiseSign.java" file checks if it is directional. It seems the signs must be placed on the side of a block to be a directional instance and not on top of a block.
Cruise signs do work if they are placed on the side of a block and not on the top of a block where I guess the block data is not an instance of Directional. 
Based on this, cruise signs work but only under the condition that they are placed on the side of a block. 

Thank you for checking this bug and providing the 1.20.4 dev build. 

Side note: while messing around with this I found that helm signs cannot be destroyed in this version unless the block it is attached to is broken. Not sure if this was already known but is just a very minor thing I noticed.

**Comment by TylerS1066** [comment]
> Based on this, cruise signs work but only under the condition that they are placed on the side of a block.

Ah yes, I should have mentioned that.

> Side note: while messing around with this I found that helm signs cannot be destroyed in this version unless the block it is attached to is broken. Not sure if this was already known but is just a very minor thing I noticed.

Huh, that probably makes sense.  I'll file another issue to track that behavior.
