### ISSUE TITLE
Players not being moved in crafts

### ISSUE THREAD

**Issue by Inclyte** [APDevTeam/Movecraft#65]
Whenever I was ascending or moving towards any direction not using cruise, the craft would not bring myself with it. Causing me to fall out of the craft.

**Comment by eirikh1996** [comment]
Stick moving is not moving me much

**Comment by TylerS1066** [comment]
Some more details:
It only seems to occur if the player is standing on the very top of a craft or the very bottom of a craft.

**Comment by wolfebersahd** [comment]
This one stipulates not using cruise.

I haven't seen an issue falling of ships while stick piloting yet. Which is why I wrote #86.

I don't think #93 is the same as mine as I've been testing my ships almost exclusively in OP and still experience #86.

I can definitely test perms, all my testers currently have movecraft.*

**Comment by TylerS1066** [comment]
This one originally is using either cruise or not, sorry that I forgot to clarify that.

#86 was just adding more cases for when players fall off of a craft, that being the aft (cruise-skip-blocks) blocks of the ship.  But since this is the only issue that I've been able to replicate, this is the one I wanted to use as the default.  If you can get your issue to a point where it can be easily replicated (like this one is) then we can add it to the list of player movement cases in this issue.

I agree #93 is different, as it has a much larger scope of players falling off (as demonstrated in the gif) but since neither of us have had the issue or can replicate it, I see it as outside the bounds of this repo.

**Comment by wolfebersahd** [comment]
In relation to #86, I was able to narrow it down a bit.

Steps to reproduce the behavior:
1. Build a "Frigate" type ship that is 20 blocks long with a cruise skip block of 8.
2. Give the player only the movecraft.frigate.* (this is used to sell individual ship licenses or give them away as rank rewards)
3. Pilot the ship.
4. Turn Cruise on in the forward direction.
5. Walk to the back of the ship.
When there are less than 8 blocks left on the ship, player is dropped off the ship.
(This occurs 100% of the time)

If player is given movecraft.* this issues occurs with a far lower occurrence 1:30 was observed and it happened while walking up stairs on the cruising ship.

Also note i did not change any of my plugins, @FrozenBreard this could be your issue too. as OP give the movecraft.* perm and i believe you give your ships perms away in ranks.

Is there a list of perms that movecraft 7 pre_release_6 has? can you provide a list to i can test all the perms and narrow it down to which one causes #86.

**Comment by TylerS1066** [comment]
I believe these bugs were fixed in https://github.com/APDevTeam/Movecraft/commit/7afafec6677e68130679129eb9de71b4ae0e7680.

I have a compiled version [here](https://github.com/TylerS1066/Movecraft/releases/tag/7.0.0_Pre-Release_7_Canidate) with the fix, and a bunch of the recent features.

@wolfebersahd you willing to test and see if your issue still shows up?

**Comment by wolfebersahd** [comment]
Sure I'll test it later tonight or tomorrow.

**Comment by FrozenBeard** [comment]
I will also give it a test tonight!

**Comment by FrozenBeard** [comment]
Tested on both my servers, players still get thrown off the crafts just like before.

**Comment by wolfebersahd** [comment]
I'm noticing a few different things, and so far I have only tested with the movecraft.* permission.

Steps to reproduce the behavior:
1. Give the player only the movecraft.* perm (OP or deOPed as long as they have the permission)
2. Pilot the ship.
3. Turn Cruise on in any direction
4. Walk around the ship
Player doesn't get teleported forward with the cruiseskipblock distance when climbing stairs or bottom placed half-slabs (this happens roughly 1/10 times) When walking on full blocks or top placed half-slabs that give an integer with no decimal location for Y location it seems to be far more stable. I was able to be on the last top placed half-slab on the back of my ship and not get dropped off, but I would get left behind 8 blocks, my cruiseskipblock amount, when I would climb stairs while it's cruising. If those stairs or bottom placed half-slabs were close enough to the back of my ship, I would have been dropped off.

** I should probably test this while walking on fences, cobble walls, etc, as it might be an issue with the getplayerlocation rounding off the decimals. (just a guess, i have no actual clue what's going on)

** I will also try testing with only the movecraft.frigate.* instead of movecraft.* to see if there's any difference in reproduction.

**Comment by cccm5** [comment]
The permission node's don't matter at all for teleportation. Anything involving them is most likely a placebo

**Comment by wolfebersahd** [comment]
Perhaps, but it doesn't hurt to be thorough, it could be a teleport cool-down somewhere that movecraft might need to bypass that an OP player gets in the case of @FrozenBeard 's issue.

**Comment by cccm5** [comment]
The section of code involving teleportation is very small, there is nothing related to permissions. Please don't waste your efforts. I'm fairly sure the issue is due to how teleportation is done and is most likely caused be different versions.

**Comment by TylerS1066** [comment]
All the testing I've done has been 1.10.2 spigot, and I do not see either of the issues with permissions or falling off at all, even with only movecraft.airship.* perms.

**Comment by wolfebersahd** [comment]
I'm on spigot 1.12.2 as per my original bug write up of #86.

Is movecraft 7 being written for 1.10 or 1.12? I know 1.13 won't be for another while because of the flattening. 

The movecraft I currently use on both my server that is stable, but laggy is 5.5. 

Movecraft 6 is incompatible with 1.12.2.

Testing movecraft on differen server versions is a good thing. Limiting you bug checking and regression to only 1.10. May be why you're not seeing our bugs.

**Comment by TylerS1066** [comment]
Agreed that my testing on 1.10.2 is limiting, and 7.0 is being written for 1.10 to 1.12, but my concern is solely 1.10 as that is the only version our server will use.

**Comment by wolfebersahd** [comment]
That's a bit concerning for servers that want to use Movecraft and move onto newer version. If the code owner team will proprietary run on Movecraft 1.10.2 there is little use fixing issues that involve other version, like the issue @FrozenBeard and I are having.

Consequently if it's being written for 1.10 to 1.12 it should be checked across those version and not solely checked on 1.10.

Don't get me wrong, I appreciate all that you're all doing to update and improve Movecraft. I'm trying to do my part in providing very descriptive and accurate bugs. But it's a bit worrisome to hear that your concern is solely for 1.10.2 support.

**Comment by wolfebersahd** [comment]
My live servers are still using Movecraft 5.5.

I meant no disrespect. I'm unaware of how you're all working internally on it and was concerned that Tyler's focus was shared by the entire team, I apologise for my assumption.

**Comment by FrozenBeard** [comment]
How do we fix this issue? Either way permissions have some play in it, as if I /op or give myself elevated permissions it doesn't throw me off a craft. So that's 2 of us that have figured this now!
I'm not sure how else I can help out? 
I'm using 1.12.2 for the books, but I want to move to 1.13 asap, as 1.14 test server is already up for Spigot!

**Comment by TylerS1066** [comment]
> How do we fix this issue?

For 1.12 and the weird permissions interactions, cc says it can't be something within movecraft and is probably something external.

Have you tested it with just a blank 1.12 server (with a permissions plugin)?  I have confirmed that the snapshot I posted up there seems to work on 1.10.2 spigot (regardless of permissions), so we should try and see if the difference is just server version or if there is a plugin/permission change in addition.  If it is a server version issue then we can try to tackle it, if if is another plugin and a weird interaction we can see about it then, and if it is a permission issue inside movecraft we can fix it.

**Comment by wolfebersahd** [comment]
Please see my comment above

https://github.com/APDevTeam/Movecraft/issues/65#issuecomment-454781066

I have narrowed it down as far as I can. I will have another go at it this Saturday, Jan 26th, but don't think I'll see any difference in my reproduction steps as it's about as thorough as I can make it..

I have no conflicting permissions, weather I give them "movecraft.airship.*" or simply "movecraft.*" the above still happens at the frequency listed. It's not consistent either. I've tested with OPed and un-OPed players and both have experiences similar behavior to my comment above, getting ignored by the movecraft cruiseskipblocks when transitioning from planks to slabs, and fenced and ladders, etc.

@FrozenBeard, a no-cheat or anti-cheat plugin can play around with how players get teleported around, being OPed will usually bypass those permissions. I recall having a block elevator that kicked people for flying, because the speed at which the elevator moved downwards caused the player to not hit the ground for a while.... you may be experiencing a similar issue. If you use luckperms you can use the `/lp verbose` command to check and see what permission is being called and checked, you would need to do this with only 1 other player online as multiple player will flood the logs rather quickly.

**Comment by FrozenBeard** [comment]
Bump, I still can't use this plugin due to this bug.

**Comment by Pulverizer** [comment]
I've got a similar issue with my Sponge port.
Not tested a possible fix yet as not at PC. 
Might be caused by Async Manager possibly calling Task#getUpdates() before the Task has finished running, therefore causing it to not pass on the EntityUpdateCommands.

**Comment by cccm5** [comment]
Fixed in latest pre-release

**Comment by wolfebersahd** [comment]
@cccm5 

I just spent the last 45 minutes testing this.
Server: 1.12.2 (latest 1.12.2 build) hosted on my local PC
Movecraft Version: Movecraft 7.0.0_Pre-release_7
Clean world, with only EssentialsX installed with it.

For me I noticed a remarkable stability increase, I was able to move around my craft with fluidity.

Although I still got dropped off my craft once in that time frame, my testing buddy who was connecting to me remotely from a distance fell off 4-5 times in less than 10 minutes. The in game "ping" was full bars for both of us. Could it be a latency issue?

I will be moving this to my closed beta server and testing it on a dedicated host later or this weekend.

I attached my craft file for reference.

[Frigate.txt](https://github.com/APDevTeam/Movecraft/files/3214670/Frigate.txt)

**Comment by cccm5** [comment]
Ya, I've seen some reports from another server as well saying they still have issues. By any chance, are you using paper?

**Comment by wolfebersahd** [comment]
Nope pure 1.12.2 Spigot. 

The other server is PirateCraft or PirateMC right. Owner is FrozenBeard/GodsDead?

**Comment by FrozenBeard** [comment]
Yarp! Same issue for me too, even with just moving without cruise so it's not and overloading issue, some wonky logic somewhere.

**Comment by wolfebersahd** [comment]
@cccm5 

I hate to be the bearer of bad news, but after 16 days of testing/using Pre-Release_8 I had a player fall of the back of a ship while cruising with cruise-skip-blocks of 8.

It's only been one instance, but I'll try to reproduce this again if I can.

The player in question had a very weak connection (playing wireless-ly 2 floors away from the router. His connection was spotty and dropped off the server a few times. So latency/lag on his end might have played a part in it.

**Comment by cccm5** [comment]
Latency in connection would probably cause something like that to happen, but please keep me posted if it happens again. The plugin can't handle all situations, which is why there's a built in mechanism to get back to your ship (`/manoverboard`) that can be used if you happen to fall out.

**Comment by wolfebersahd** [comment]
Simple for use on a water based server, not so simple on a skylands server, where typing /-m-a-n-o-v-e-r-b-o-a-r-d while falling into the void or onto land is deadly :(. I may re-alias it to something shorter.

I'll keep you posted.

**Comment by FrozenBeard** [comment]
well no, its not on a water based server either! The ship just carry's on and dousn't stop when the users thrown off the ship! It will just keep going like a torpedo, and they will do manoverboard and get thrown off time after time and then they will loose their ship aswell! 
I'm tempted to throw the pre release onto my production as its the best way to test hardcore, people will moan if there is any issues.

**Comment by wolfebersahd** [comment]
I have pre-release 8 on my production server for over a month now, and there has been ZERO falling off ships. (That server doesn't have any ships that can cruise). My players have been warned, but they also enjoy the increase stability and reduced lag from this build.

The same pre-release on my test server which has cruise (with a high cruise skip block of 8) has had two of my other staff members fall off a ship in two very different situations. One for latency issues, and the other for running around, climbing ladders and jumping around a cruising ship (it happened while walking up stairs to be precise). I was unable to reproduce them.

On a water based server typing `/release` is very effective in stopping a ship and then swimming to it. Even `/manoverboard` followed by `/release` is manageable.

On an airship server, it is very difficult to type `/manoverboard` before dying of fall damage.

**Comment by cccm5** [comment]
Thanks for the info, hopefully it will help narrow down the cause.
